// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;

[assembly: AssemblyVersion("1.1.343.2690")]
[assembly: AssemblyFileVersion("1.01.343.2690")]
